Repository IcePingus/project_CPO_N7, pull requests merged in 2023-06, with the labels that each got.

#18 US-109 : Added bucket tool
  src/graphic/model/tools/BucketTool.java
  src/graphic/model/tools/HighlighterTool.java
  src/graphic/model/tools/PencilTool.java
  src/graphic/model/tools/PickerTool.java
  src/graphic/model/tools/RubberTool.java
  src/graphic/model/tools/ToolCommand.java
  src/graphic/view/CanvaPanel.java
Labels: Sprint 2, Vérifié

#16 US-103 : SVGCanva
  src/terminalSVG/controller/ControllerTerminalPanel.java
  src/terminalSVG/model/Command.java
  src/terminalSVG/model/History.java
  src/terminalSVG/model/SVGPreview.java
  src/terminalSVG/view/TerminalProjectPanel.java
  src/terminalSVG/view/ViewHistoryPanel.java
  src/terminalSVG/view/ViewSVGCanvaPreviewPanel.java
Labels: Sprint 2, Vérifié

#19 US-207 : Add Picker tool
  src/graphic/controller/ColorController.java
  src/graphic/model/color/ColorModel.java
  src/graphic/model/tools/BucketTool.java
  src/graphic/model/tools/HighlighterTool.java
  src/graphic/model/tools/PencilTool.java
  src/graphic/model/tools/PickerTool.java
  src/graphic/view/CanvaPanel.java
  src/graphic/view/ColorSchemeInternalFrame.java
  src/graphic/view/GraphicProjectPanel.java
  src/graphic/view/ToolInternalFrame.java
Labels: Sprint 2, Vérifié

#21 US-315 : b&w transform
  src/graphic/view/CanvaPanel.java
  src/graphic/view/GraphicProjectPanel.java
Labels: À vérifier, Sprint 2

#24 FIX-201 : Fixed bucket bug
  src/graphic/view/CanvaPanel.java
Labels: Sprint 2, Vérifié

#25 US-316 : add flip image
  src/graphic/view/CanvaPanel.java
  src/graphic/view/GraphicProjectPanel.java
Labels: Sprint 3, Vérifié

#28 US-317 : clear image
  export/empty
  src/graphic/view/CanvaPanel.java
  src/graphic/view/GraphicProjectPanel.java
Labels: Sprint 3, Vérifié

#29 US-318 : refacto
  src/graphic/view/CanvaPanel.java
  src/graphic/view/GraphicProjectPanel.java
Labels: Sprint 3, Vérifié

#30 Update branch + refactored canva
  src/graphic/controller/CanvaController.java
  src/graphic/model/canva/Canva.java
  src/graphic/model/tools/BucketTool.java
  src/graphic/model/tools/HighlighterTool.java
  src/graphic/model/tools/PencilTool.java
  src/graphic/model/tools/PickerTool.java
  src/graphic/model/tools/RubberTool.java
  src/graphic/model/tools/ToolCommand.java
  src/graphic/model/tools/Toolbox.java
  src/graphic/view/CanvaPanel.java
  src/graphic/view/GraphicProjectPanel.java
  src/graphic/view/ResizeDialog.java
  src/graphic/view/ToolInternalFrame.java
Labels: À vérifier, Sprint 3, Vérifié

#32 US-319 : setjmenubar
  src/graphic/controller/CanvaController.java
Labels: À vérifier, Sprint 3

#36 US 202 : Suppresion de formes
  src/terminalSVG/controller/ControllerTerminalPanel.java
  src/terminalSVG/model/SVGCommand/CircleSVG.java
  src/terminalSVG/model/SVGCommand/ClearSVG.java
  src/terminalSVG/model/SVGCommand/DrawShapeAction.java
  src/terminalSVG/model/SVGCommand/EraseSVG.java
  src/terminalSVG/model/SVGCommand/OvalSVG.java
  src/terminalSVG/model/SVGCommand/PolygonSVG.java
  src/terminalSVG/model/SVGCommand/RectangleSVG.java
  src/terminalSVG/model/SVGCommand/SVGCommand.java
  src/terminalSVG/model/SVGCommand/SquareSVG.java
  src/terminalSVG/model/SVGPreview.java
  src/terminalSVG/model/parser/Parser.java
Labels: Sprint 3, Vérifié

#38 US-204 : Added color command
  src/terminalSVG/controller/ControllerTerminalPanel.java
  src/terminalSVG/model/SVGCommand/ColorSVG.java
  src/terminalSVG/model/SVGPreview.java
  src/terminalSVG/model/parser/Parser.java
Labels: À vérifier, Sprint 3

#39 US-323 : add text
  src/assets/images/text.png
  src/graphic/controller/CanvaController.java
  src/graphic/model/canva/Canva.java
  src/graphic/model/tools/BucketTool.java
  src/graphic/model/tools/HighlighterTool.java
  src/graphic/model/tools/PencilTool.java
  src/graphic/model/tools/PickerTool.java
  src/graphic/model/tools/RubberTool.java
  src/graphic/model/tools/TextTool.java
  src/graphic/model/tools/ToolCommand.java
  src/graphic/model/tools/Toolbox.java
  src/graphic/view/ToolInternalFrame.java
Labels: À vérifier, Sprint 3

#46 US-405 : save image
  src/graphic/controller/CanvaController.java
  src/graphic/exception/BadFormatException.java
Labels: À vérifier, Sprint 4

#45 US-402 : paste image
  src/graphic/controller/CanvaController.java
  src/graphic/exception/ClipboardVoidException.java
  src/graphic/view/GraphicProjectPanel.java
Labels: À vérifier, Sprint 4

#44 US-301 : Ajout Command SaveSVG
  src/terminalSVG/controller/ControllerTerminalPanel.java
  src/terminalSVG/model/SVGCommand/SaveSVG.java
  src/terminalSVG/model/SVGPreview.java
Labels: À vérifier, Sprint 4

#48 US-404 : Added keyboards shortcuts
  src/graphic/controller/CanvaController.java
  src/graphic/model/canva/Canva.java
  src/graphic/model/tools/TextTool.java
  src/graphic/view/ColorSchemeInternalFrame.java
  src/graphic/view/GraphicProjectPanel.java
Labels: À vérifier, Sprint 4

#52 US-306 : RecolorSVG Command
  src/terminalSVG/controller/ControllerTerminalPanel.java
  src/terminalSVG/model/SVGCommand/DrawShapeAction.java
  src/terminalSVG/model/SVGCommand/RecolorSVG.java
  src/terminalSVG/model/SVGPreview.java
Labels: À vérifier, Sprint 4

#53 US-303 : TranslationY Command
  src/terminalSVG/controller/ControllerTerminalPanel.java
  src/terminalSVG/model/SVGCommand/CircleSVG.java
  src/terminalSVG/model/SVGCommand/DrawShapeAction.java
  src/terminalSVG/model/SVGCommand/OvalSVG.java
  src/terminalSVG/model/SVGCommand/PolygonSVG.java
  src/terminalSVG/model/SVGCommand/RectangleSVG.java
  src/terminalSVG/model/SVGCommand/SquareSVG.java
  src/terminalSVG/model/SVGCommand/TranslateXSVG.java
  src/terminalSVG/model/SVGCommand/TranslateYSVG.java
  src/terminalSVG/model/SVGPreview.java
Labels: À vérifier, Sprint 4

#54 US-304 : TranslateSVG Command
  src/terminalSVG/controller/ControllerTerminalPanel.java
  src/terminalSVG/model/SVGCommand/CircleSVG.java
  src/terminalSVG/model/SVGCommand/DrawShapeAction.java
  src/terminalSVG/model/SVGCommand/OvalSVG.java
  src/terminalSVG/model/SVGCommand/PolygonSVG.java
  src/terminalSVG/model/SVGCommand/RectangleSVG.java
  src/terminalSVG/model/SVGCommand/SquareSVG.java
  src/terminalSVG/model/SVGCommand/TranslateSVG.java
  src/terminalSVG/model/SVGCommand/TranslateXSVG.java
  src/terminalSVG/model/SVGCommand/TranslateYSVG.java
  src/terminalSVG/model/SVGPreview.java
Labels: À vérifier, Sprint 4

#55 US-304fix : Update translate Shapes
  src/terminalSVG/model/SVGCommand/OvalSVG.java
  src/terminalSVG/model/SVGCommand/PolygonSVG.java
  src/terminalSVG/model/SVGCommand/RectangleSVG.java
  src/terminalSVG/model/SVGCommand/SquareSVG.java
Labels: Sprint 4, Vérifié

#56 US-401 : Added zoom
  src/graphic/controller/CanvaController.java
  src/graphic/model/canva/Canva.java
Labels: Sprint 4, Vérifié

#57 Javadoc svg
  src/terminalSVG/controller/ControllerTerminalPanel.java
  src/terminalSVG/model/Command.java
  src/terminalSVG/model/History.java
  src/terminalSVG/model/SVGCommand/CircleSVG.java
  src/terminalSVG/model/SVGCommand/ClearSVG.java
  src/terminalSVG/model/SVGCommand/ColorSVG.java
  src/terminalSVG/model/SVGCommand/DrawShapeAction.java
  src/terminalSVG/model/SVGCommand/EraseSVG.java
  src/terminalSVG/model/SVGCommand/OvalSVG.java
  src/terminalSVG/model/SVGCommand/Point.java
  src/terminalSVG/model/SVGCommand/PolygonSVG.java
  src/terminalSVG/model/SVGCommand/RecolorSVG.java
  src/terminalSVG/model/SVGCommand/RectangleSVG.java
  src/terminalSVG/model/SVGCommand/RenameSVG.java
  src/terminalSVG/model/SVGCommand/SVGCommand.java
  src/terminalSVG/model/SVGCommand/SaveSVG.java
  src/terminalSVG/model/SVGCommand/SquareSVG.java
  src/terminalSVG/model/SVGCommand/TranslateSVG.java
  src/terminalSVG/model/SVGPreview.java
  src/terminalSVG/model/parser/CommandParser.java
  src/terminalSVG/model/parser/Parser.java
  src/terminalSVG/view/TerminalProjectPanel.java
  src/terminalSVG/view/ViewHistoryPanel.java
  src/terminalSVG/view/ViewSVGCanvaPreviewPanel.java
  src/terminalSVG/view/ViewSVGCodePreviewPanel.java
Labels: Sprint 4, Vérifié

#61 US-408-2 : junit + some fix
  export/empty
  src/Test/graphic/TestCanvaController.java
  src/graphic/controller/CanvaController.java
  src/graphic/model/canva/Canva.java
  src/graphic/view/GraphicProjectPanel.java
Labels: Sprint 4, Vérifié

#59 US-310 : Ajout ResizeSVG Command
  src/terminalSVG/controller/ControllerTerminalPanel.java
  src/terminalSVG/model/SVGCommand/CircleSVG.java
  src/terminalSVG/model/SVGCommand/DrawShapeAction.java
  src/terminalSVG/model/SVGCommand/OvalSVG.java
  src/terminalSVG/model/SVGCommand/PolygonSVG.java
  src/terminalSVG/model/SVGCommand/RectangleSVG.java
  src/terminalSVG/model/SVGCommand/ResizeSVG.java
  src/terminalSVG/model/SVGCommand/SquareSVG.java
  src/terminalSVG/model/SVGPreview.java
Labels: À vérifier, Sprint 4

#62 US-410 : toolbar & background image
  src/FramePinte.java
  src/Test/graphic/TestBucketTool.java
  src/Test/graphic/TestCanvaController.java
  src/Test/graphic/TestHighlighterTool.java
  src/Test/graphic/TestImageComparator.java
  src/Test/graphic/TestPencilTool.java
  src/Test/graphic/TestPickerTool.java
  src/Test/graphic/TestRubberTool.java
  src/Test/graphic/TestTextTool.java
  src/assets/images/background.png
  src/assets/images/logo.png
  src/graphic/model/canva/Canva.java
  src/graphic/view/GraphicProjectPanel.java
  src/graphic/view/SelectionPanel.java
Labels: Sprint 4, Vérifié

#63 US-208 : Add Stroke size for ShapeTool except Circle
  src/graphic/model/canva/Canva.java
  src/graphic/model/color/ColorModel.java
  src/graphic/model/tools/ShapeTool.java
  src/graphic/view/ToolInternalFrame.java
Labels: Sprint 4, Vérifié

#65 US-411 : javadoc graphic
  src/graphic/controller/CanvaController.java
  src/graphic/controller/ColorController.java
  src/graphic/exception/BadFormatException.java
  src/graphic/exception/ClipboardVoidException.java
  src/graphic/exception/nullImageException.java
  src/graphic/model/canva/Canva.java
  src/graphic/model/color/ColorModel.java
  src/graphic/model/tools/BucketTool.java
  src/graphic/model/tools/HighlighterTool.java
  src/graphic/model/tools/PencilTool.java
  src/graphic/model/tools/PickerTool.java
  src/graphic/model/tools/RubberTool.java
  src/graphic/model/tools/ShapeTool.java
  src/graphic/model/tools/TextTool.java
  src/graphic/model/tools/ToolCommand.java
  src/graphic/model/tools/Toolbox.java
  src/graphic/view/ColorSchemeInternalFrame.java
  src/graphic/view/GraphicProjectPanel.java
  src/graphic/view/ResizeDialog.java
  src/graphic/view/SelectionPanel.java
  src/graphic/view/ToolInternalFrame.java
Labels: Sprint 4, Vérifié

#66 Us 406
  src/Test/graphic/TestImageComparator.java
  src/Test/terminal/TestCircleSVG.java
  src/Test/terminal/TestModifier.java
  src/Test/terminal/TestRectangleSVG.java
  src/Test/terminal/TestSquareSVG.java
  src/graphic/view/GraphicProjectPanel.java
  src/graphic/view/SelectionPanel.java
  src/terminalSVG/controller/ControllerTerminalPanel.java
  src/terminalSVG/model/Command.java
  src/terminalSVG/model/History.java
  src/terminalSVG/model/SVGCommand/CircleSVG.java
  src/terminalSVG/model/SVGCommand/ClearSVG.java
  src/terminalSVG/model/SVGCommand/ColorSVG.java
  src/terminalSVG/model/SVGCommand/DrawShapeAction.java
  src/terminalSVG/model/SVGCommand/EraseSVG.java
  src/terminalSVG/model/SVGCommand/OvalSVG.java
  src/terminalSVG/model/SVGCommand/Point.java
  src/terminalSVG/model/SVGCommand/PolygonSVG.java
  src/terminalSVG/model/SVGCommand/RecolorSVG.java
  src/terminalSVG/model/SVGCommand/RectangleSVG.java
  src/terminalSVG/model/SVGCommand/RenameSVG.java
  src/terminalSVG/model/SVGCommand/ResizeSVG.java
  src/terminalSVG/model/SVGCommand/SVGCommand.java
  src/terminalSVG/model/SVGCommand/SaveSVG.java
  src/terminalSVG/model/SVGCommand/SquareSVG.java
  src/terminalSVG/model/SVGCommand/TranslateSVG.java
  src/terminalSVG/model/SVGPreview.java
  src/terminalSVG/model/parser/CommandParser.java
  src/terminalSVG/model/parser/Parser.java
  src/terminalSVG/view/TerminalProjectPanel.java
  src/terminalSVG/view/ViewHistoryPanel.java
  src/terminalSVG/view/ViewSVGCanvaPreviewPanel.java
  src/terminalSVG/view/ViewSVGCodePreviewPanel.java
Labels: Sprint 4, Vérifié

#67 US-413 : Added move tool and image icon to the application
  src/FramePinte.java
  src/assets/images/move.png
  src/graphic/model/canva/Canva.java
  src/graphic/model/tools/MoveTool.java
  src/graphic/view/ToolInternalFrame.java
Labels: À vérifier, Sprint 4

#69 US-412 : Added ToolController + cleaned code
  src/core/FramePinte.java
  src/core/SelectionPanel.java
  src/graphic/controller/CanvaController.java
  src/graphic/controller/ToolController.java
  src/graphic/exception/NullImageException.java
  src/graphic/model/canva/Canva.java
  src/graphic/model/tools/HighlighterTool.java
  src/graphic/model/tools/MoveTool.java
  src/graphic/model/tools/PencilTool.java
  src/graphic/model/tools/PickerTool.java
  src/graphic/model/tools/RubberTool.java
  src/graphic/model/tools/ShapeTool.java
  src/graphic/model/tools/TextTool.java
  src/graphic/model/tools/ToolCommand.java
  src/graphic/model/tools/Toolbox.java
  src/graphic/view/ColorSchemeInternalFrame.java
  src/graphic/view/GraphicProjectPanel.java
  src/graphic/view/ResizeDialog.java
  src/graphic/view/ToolInternalFrame.java
  src/test/graphic/ImageComparator.java
  src/test/graphic/LoadImage.java
  src/test/graphic/TestImageComparator.java
Labels: Sprint 4, Vérifié

#70 Us 203 : Help Command & Refacto
  src/terminalSVG/controller/ControllerTerminalPanel.java
  src/terminalSVG/model/Instruction.java
  src/terminalSVG/model/SVGCommand/CircleSVG.java
  src/terminalSVG/model/SVGCommand/ClearSVG.java
  src/terminalSVG/model/SVGCommand/ColorSVG.java
  src/terminalSVG/model/SVGCommand/DrawShapeAction.java
  src/terminalSVG/model/SVGCommand/EraseSVG.java
  src/terminalSVG/model/SVGCommand/HelpSVG.java
  src/terminalSVG/model/SVGCommand/OvalSVG.java
  src/terminalSVG/model/SVGCommand/Point.java
  src/terminalSVG/model/SVGCommand/PolygonSVG.java
  src/terminalSVG/model/SVGCommand/RecolorSVG.java
  src/terminalSVG/model/SVGCommand/RectangleSVG.java
  src/terminalSVG/model/SVGCommand/RenameSVG.java
  src/terminalSVG/model/SVGCommand/ResizeSVG.java
  src/terminalSVG/model/SVGCommand/SVGCommand.java
  src/terminalSVG/model/SVGCommand/SaveSVG.java
  src/terminalSVG/model/SVGCommand/SquareSVG.java
  src/terminalSVG/model/SVGCommand/TranslateSVG.java
  src/terminalSVG/model/SVGPreview.java
  src/terminalSVG/model/parser/CommandParser.java
  src/terminalSVG/model/parser/Parser.java
  src/terminalSVG/view/ViewHistoryPanel.java
  src/test/terminal/TestCircleSVG.java
  src/test/terminal/TestModifier.java
  src/test/terminal/TestRectangleSVG.java
  src/test/terminal/TestSquareSVG.java
Labels: Sprint 4, Vérifié

#71 US-414 : refacto canvaComponent
  src/graphic/controller/CanvaController.java
  src/graphic/model/ToolContext.java
  src/graphic/model/canva/Canva.java
  src/graphic/model/tools/HighlighterTool.java
  src/graphic/model/tools/MoveTool.java
  src/graphic/model/tools/PencilTool.java
  src/graphic/model/tools/RubberTool.java
  src/graphic/model/tools/ShapeTool.java
  src/graphic/model/tools/TextTool.java
  src/graphic/view/CanvaComponent.java
  src/graphic/view/GraphicProjectPanel.java
  src/test/graphic/TestBucketTool.java
  src/test/graphic/TestCanva.java
  src/test/graphic/TestCanvaController.java
  src/test/graphic/TestHighlighterTool.java
  src/test/graphic/TestPencilTool.java
  src/test/graphic/TestPickerTool.java
  src/test/graphic/TestRubberTool.java
  src/test/graphic/TestTextTool.java
Labels: À vérifier, Sprint 4
